<template>
    <div class="mt-5 data-table">
        
        <v-btn v-if="saveBtn" :disabled="!this.data.length" @click="createPDF" class='primary'>
            <span>Save as PDF</span>
            <v-icon right>download</v-icon>
        </v-btn>

        <v-data-table
        ref="table"
        :headers="headers"
        :items="data"
        item-key="name"
        class="elevation-1 mb-5"
        @click:row="editRow"
        :search="search"
        :tableName="tableName"
        >

        <template v-slot:top>
            <v-text-field
            v-model="search"
            label="Search"
            class="mx-4"
            ></v-text-field>
        </template>

        <template v-slot:item.delete="{ item }">
            <v-btn
            v-model="item.delete" 
            class="red white--text"
            @click="delItem(item)"
            :disabled = "item.status == 'Accepted'"
            >
                <v-icon>
                    delete
                </v-icon>
            </v-btn>
        </template>

        </v-data-table>
    </div>
</template>

<script>
import axios from 'axios';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default {
  name: "DataTable",
  components: {
  },  
  props: ['data', 'headers', 'goToLink', 'tableName'],
  created () {
      //only Bank Per are allowed to generate reports
        if(localStorage.getItem('user-type') === "Bank Per")
            this.saveBtn = true;
    },
  data:() => ({
        search: '',
        saveBtn: false,
}),
  methods: {
    delItem(item) {
        let id = item.id;
        let idx = this.data.indexOf(item);
        this.data.splice(idx, 1);
        
        axios.delete(`api${this.goToLink}${id}/`,
        {
            headers: {"Authorization" : `Token ${localStorage.getItem('user-token')}`},
        })
        .then(resp => {
            console.log(resp.data);
        })
        .catch(err => {
            console.log(err); 
        })  
    },
    editRow(row) {
        let route = this.$route.name;
        if (route === "ListFundApps"){
            this.$router.push(`/fundapps/${row.id}`);
        }
        else if (route === "ListLoanApps"){
            this.$router.push(`/loanapps/${row.id}`);
        }
    },
    createPDF () {
        let dataSource = this.$refs.table.items,
            headerSource =  this.headers;
        let columnHeader = [];
        let rows = [];
        let doc = new jsPDF();
        
        let properties = [];
        headerSource.forEach(element => {
            let temp = [];
            for (let key in element) {
                temp.push(element[key])
            }
            if(temp[0] != "Delete"){
                columnHeader.push(temp[0]);
                properties.push(temp[1]);
            }
        }); 
        // console.log(properties);

        dataSource.forEach(element => {
            let temp = [];
            console.log(element);
            for (let i=0; i<properties.length; i++) {
                if(properties[i] === "fund_type"){
                    temp.push(element[properties[i]]);
                }
                else
                    temp.push(element[properties[i]]);
            }
            console.log(temp);
            rows.push(temp);
        });
        doc
        .setFont("helvetica")
        .setFontSize(16)
        .text(`${this.tableName} table`, 15, 10, { align: "left" });


    
         doc
        .setFont("helvetica")
        .setFontSize(13)
        .text(`Generated By: ${localStorage.getItem('username')}`, 15, 20, { align: "left" });

         doc
        .setFont("helvetica")
        .setFontSize(13)
        .text(`Generated At: ${new Date().toISOString().slice(0, 10)}`, 140, 20, { align: "left" });

    
    
        doc.autoTable(columnHeader, rows, { startY: 25 });
        doc.save(this.tableName + '.pdf');

    }
  }
};
</script>