# Generated by Django 3.1.7 on 2021-03-23 23:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveIntegerField()),
                ('max_amount', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('interest_rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)])),
                ('fund_type', models.CharField(choices=[('CR', 'Car'), ('MG', 'Mortgage'), ('PR', 'Personal')], default='PR', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoanFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveIntegerField()),
                ('max_amount', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('interest_rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)])),
                ('fund_type', models.CharField(choices=[('CR', 'Car'), ('MG', 'Mortgage'), ('PR', 'Personal')], default='PR', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoanFundApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('RJ', 'Rejected'), ('AC', 'Accepted')], default='PN', max_length=20)),
                ('loan_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_apps', to='bankLoans.loanfund')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('RJ', 'Rejected'), ('AC', 'Accepted')], default='PN', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_apps', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_apps', to='bankLoans.loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='bankLoans.loanfund'),
        ),
    ]
