# Generated by Django 3.1.7 on 2021-03-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankLoans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='fund_type',
        ),
    ]
