# Generated by Django 3.1.7 on 2021-03-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankLoans', '0004_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_type',
        ),
    ]
