# Generated by Django 3.1.7 on 2021-03-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankLoans', '0005_remove_account_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('Bank Per', 'Bank Personnel'), ('PROV', 'Provider'), ('CUST', 'Customer')], default='CUST', max_length=20),
        ),
    ]
